title: "Aditya Chauhan"
description: "PhD Student in Mathematical Finance at IIT Kanpur"
theme: minima

author:
  name: Aditya Chauhan
  email: your-email@example.com

minima:
  social_links:
    github: yourgithubusername
    linkedin: yourlinkedinusername

header_pages:
  - research.md
  - projects.md
  - cv.md

plugins:
  - jekyll-feed
